### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [xdtianyu/Gallery#2]
With no commits for more than 2 years I wonder: do you still maintain this project, @xdtianyu?

**Comment by xdtianyu** [comment]
Yes, this project will be continued, but currently I do not have much time for this one, 
I expect to have time in the coming months. @IzzySoft

**Comment by IzzySoft** [comment]
Thanks for the heads-up and good news! All the best then for future development (and plenty of free time 😃 )
